app_name  = "GotchaBeta"
bind_ip   = "127.0.0.1"
bind_port = 8080
store     = "redis"                    # default

[logger_configuration]
    show_caller   = true
    level         = "debug"
    output_format = "terminal-colored" # terminal, json

[database_configuration]
    host = "server"
    port = 5432
    username = "postgres"
    database = "gotcha"
    ssl_mode = "disable"

[redis_configuration]
    host = "server"
    port = 6379
    session_lifetime = 2592000         # 30 days
    idle_connections = 10